import { GBA_CONFIG } from './GBAConfig';

// Legacy config maintained for compatibility, using GBA-authentic values
export const GAME_CONFIG = {
  // Display settings (GBA resolution scaled up)
  SCREEN_WIDTH: GBA_CONFIG.SCREEN.WIDTH,
  SCREEN_HEIGHT: GBA_CONFIG.SCREEN.HEIGHT,
  SCALE_FACTOR: GBA_CONFIG.SCREEN.SCALE,
  
  // Player settings (using GBA-authentic balance)
  PLAYER: {
    MOVE_SPEED: GBA_CONFIG.BALANCE.PLAYER.MOVE_SPEED,
    MAX_HEALTH: GBA_CONFIG.BALANCE.PLAYER.STARTING_HEALTH,
    MAX_ENERGY: GBA_CONFIG.BALANCE.PLAYER.STARTING_ENERGY,
    ENERGY_RECHARGE_RATE: GBA_CONFIG.BALANCE.PLAYER.ENERGY_RECHARGE_RATE,
    ATTACK_COOLDOWN: GBA_CONFIG.MECHANICS.COMBAT.PUNCH_COOLDOWN,
  },
  
  // Combat settings (matching original game balance)
  COMBAT: {
    MELEE_DAMAGE: GBA_CONFIG.BALANCE.PLAYER.PUNCH_DAMAGE,
    KI_BLAST_DAMAGE: GBA_CONFIG.BALANCE.PLAYER.KI_BLAST_DAMAGE,
    KI_BLAST_COST: GBA_CONFIG.BALANCE.PLAYER.KI_BLAST_COST,
    KI_BLAST_SPEED: 12, // Slightly slower for better gameplay
    MELEE_RANGE: 1.3, // Improved melee range
    INVINCIBILITY_FRAMES: GBA_CONFIG.MECHANICS.COMBAT.INVINCIBILITY_FRAMES,
  },
  
  // Enemy settings (using balanced GBA values)
  ENEMIES: {
    WOLF: {
      HEALTH: GBA_CONFIG.BALANCE.ENEMIES.WOLF.HEALTH,
      DAMAGE: GBA_CONFIG.BALANCE.ENEMIES.WOLF.DAMAGE,
      MOVE_SPEED: GBA_CONFIG.BALANCE.ENEMIES.WOLF.MOVE_SPEED,
      ATTACK_RANGE: GBA_CONFIG.BALANCE.ENEMIES.WOLF.ATTACK_RANGE,
      DETECTION_RANGE: GBA_CONFIG.BALANCE.ENEMIES.WOLF.DETECTION_RANGE,
      EXP_REWARD: GBA_CONFIG.BALANCE.ENEMIES.WOLF.EXP_REWARD,
      ATTACK_COOLDOWN: GBA_CONFIG.BALANCE.ENEMIES.WOLF.ATTACK_COOLDOWN,
    }
  },
  
  // Game mechanics (using original game progression)
  MECHANICS: {
    SAVE_POINTS: GBA_CONFIG.MECHANICS.SAVE_POINTS,
    EXP_MULTIPLIER: GBA_CONFIG.MECHANICS.LEVEL_PROGRESSION.EXP_MULTIPLIER,
    ENERGY_DRAIN_RATE: 8, // Balanced flying energy drain
    DEATH_PENALTY: GBA_CONFIG.MECHANICS.DEATH_PENALTY,
  }
};
